import React from 'react';
import BackButton from './BackButton';

const PrivacyPolicy = () => {
  return (
    <section id="privacy-policy" className="py-10 bg-white text-gray-800">
      <BackButton />
      <div className="max-w-5xl mx-auto px-6">
        <h1 className="text-4xl font-bold text-center mb-8">
          Privacy Policy for <span className="text-gradient">Biro Cabs</span>
        </h1>
        {/* <p className="text-center text-sm text-gray-500 mb-10">Last updated: December 17, 2022</p> */}

        <div className="space-y-8 text-justify leading-7">
          <p>
            This Privacy Policy describes our policies and procedures on the collection, use, and disclosure of your
            information when you use our cab booking service. It also explains your privacy rights and how the law protects
            you.
          </p>

          <p>
            We use your personal data to provide and improve our service. By using Biro Cabs, you agree to the collection
            and use of information in accordance with this Privacy Policy.
          </p>

          <h2 className="text-2xl font-semibold">Interpretation and Definitions</h2>

          <p><strong>Interpretation:</strong> Words with capitalized initials have meanings defined below. These definitions apply equally whether in singular or plural.</p>

          <p><strong>Definitions:</strong></p>
          <ul className="list-disc pl-6">
            <li><strong>Account:</strong> A unique account created for you to access our cab services.</li>
            <li><strong>Affiliate:</strong> Any entity controlling, controlled by, or under common control with us.</li>
            <li><strong>Application:</strong> Biro Cabs, our mobile or web app-based cab booking platform.</li>
            <li><strong>Company:</strong> Refers to Biro Cabs, the cab service provider company.</li>
            <li><strong>Country:</strong> India (based in Uttar Pradesh).</li>
            <li><strong>Device:</strong> Any device used to access our services, such as a smartphone or computer.</li>
            <li><strong>Personal Data:</strong> Any data that can identify an individual.</li>
            <li><strong>Service:</strong> The cab transportation and booking platform we provide.</li>
            <li><strong>Service Provider:</strong> A third-party that processes data on behalf of the company.</li>
            <li><strong>Usage Data:</strong> Automatically collected data generated by your usage of our services.</li>
            <li><strong>You:</strong> The individual or legal entity using our service.</li>
          </ul>

          <h2 className="text-2xl font-semibold">Collecting and Using Your Personal Data</h2>
          <h3 className="text-xl font-semibold">Types of Data Collected</h3>
          <p><strong>Personal Data:</strong> Includes name, email, phone number, and usage data.</p>
          <p><strong>Usage Data:</strong> Includes IP address, browser type, device info, and interaction history with our platform.</p>
          <p><strong>Location Data:</strong> With permission, we collect location data for ride tracking and service improvements.</p>

          <h3 className="text-xl font-semibold">Use of Your Personal Data</h3>
          <p>The company may use your data to:</p>
          <ul className="list-disc pl-6">
            <li>Provide and improve the cab service</li>
            <li>Manage your account and preferences</li>
            <li>Contact you with important updates or promotions</li>
            <li>Analyze and monitor service usage</li>
            <li>Handle requests and support</li>
            <li>Perform business transactions like mergers or partnerships</li>
            <li>Ensure safety, compliance, and legal obligations</li>
          </ul>

          <h3 className="text-xl font-semibold">Sharing Your Personal Data</h3>
          <p>Your data may be shared with:</p>
          <ul className="list-disc pl-6">
            <li>Service providers for processing and operations</li>
            <li>Affiliates and partners for promotions or integrations</li>
            <li>Authorities, if required by law</li>
            <li>Third-parties with your consent</li>
          </ul>

          <h3 className="text-xl font-semibold">Retention of Your Data</h3>
          <p>We retain your data as long as necessary to provide services and comply with legal requirements.</p>

          <h3 className="text-xl font-semibold">Transfer of Data</h3>
          <p>Your data may be stored and processed outside your jurisdiction, but we ensure adequate protection wherever it resides.</p>

          <h3 className="text-xl font-semibold">Delete Your Data</h3>
          <p>You may request deletion or modification of your personal data through account settings or by contacting us.</p>

          <h3 className="text-xl font-semibold">Children's Privacy</h3>
          <p>Our services are not intended for children under 13. We do not knowingly collect data from them.</p>

          <h3 className="text-xl font-semibold">Links to Other Sites</h3>
          <p>We may link to third-party sites. We’re not responsible for their privacy practices — review their policies separately.</p>

          <h3 className="text-xl font-semibold">Changes to This Policy</h3>
          <p>We may update this Privacy Policy. You will be notified of changes through email or an app notification.</p>

          <h2 className="text-2xl font-semibold">Contact Us</h2>
          <p>If you have any questions about this Privacy Policy, you can contact us:</p>
          <ul className="list-disc pl-6">
            <li>By email: Birocabsfaridabad@gmail.com</li>
             <li>By Call: +91 9999299625</li>
          </ul>
        </div>
      </div>
    </section>
  );
};

export default PrivacyPolicy;
